# Generated by Django 3.1.3 on 2020-11-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uniquename",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Unique name for unit"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=64, verbose_name="Name"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Comment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Datasourcetype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "parser",
                    models.CharField(blank=True, max_length=100, verbose_name="Parser"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "abbreviation",
                    models.CharField(max_length=64, verbose_name="Abbreviation"),
                ),
                (
                    "symbol",
                    models.CharField(blank=True, max_length=64, verbose_name="Symbol"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Comment")),
                ("urls", models.TextField(blank=True, verbose_name="Reference URLs")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Quantities",
            },
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                ("valid", models.BooleanField(default=True, verbose_name="Valid")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="observations.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Datasource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devid", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude (dd.ddddd)"
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude (dd.ddddd)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "datalogger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasource",
                        to="observations.datasourcetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="channel",
            name="datalogger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="observations.datasource",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channels",
                to="observations.quantity",
            ),
        ),
    ]
