# Generated by Django 3.1.3 on 2020-11-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_rename_datalogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='unit',
        ),
        migrations.AddField(
            model_name='value',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='observations.channel'),
        ),
    ]
