version: "3.7"

x-base: &base
  env_file:
    - .env

services:
  endpoint:
    <<: *base
    build:
      context: ./endpoint
      target: development
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./endpoint:/app
  parser:
    <<: *base
    build:
      context: ./parser
      target: development
    restart: always
    volumes:
      - ./parser:/app
  api:
    <<: *base
    build:
      context: ./persister
      target: development
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./persister:/app
  persister:
    <<: *base
    build:
      context: ./persister
      target: development
    environment:
      CONSUMER: 1
      APPLY_MIGRATIONS: 1
      INITIALIZE_DATA: 1
    restart: always
    volumes:
      - ./persister/:/app/
