version: "3.8"

x-base: &base
  env_file:
    - ./.env.dev

services:
  endpoint:
    <<: *base
    build:
      context: ./endpoint
      target: development
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./endpoint:/app
