version: "3.8"
services:
  endpoint:
    build:
      context: ./endpoint
      target: development
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./endpoint:/app
  persister:
    build:
      context: ./persister
      target: development
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./persister:/app
