version: "3.8"

x-base: &base
  env_file:
    - ./.env.dev

services:
  endpoint:
    <<: *base
    build:
      context: ./endpoint
      target: development
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./endpoint:/app
  parser:
    <<: *base
    build:
      context: ./parser
      target: development
    restart: always
    volumes:
      - ./parser:/app
  api:
    <<: *base
    build:
      context: ./persister
      target: development
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./persister:/app
  persister:
    <<: *base
    build:
      context: ./persister
    command: python manage.py consume_parsed_data
    restart: always
    volumes:
      - ./persister/:/app/
