# Generated by Django 3.1.3 on 2021-02-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="sensortype",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensortype",
                to="parser.sensortype",
            ),
        ),
    ]
