# Generated by Django 3.1.3 on 2021-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_auto_20210210_0705"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensortype",
            name="parser",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sensornode", "sensornode"),
                    ("ultrasonic", "ultrasonic"),
                    ("dummy", "dummy"),
                ],
                max_length=100,
                verbose_name="Parser",
            ),
        ),
    ]
