# Generated by Django 3.1.3 on 2021-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_auto_20210215_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmessage',
            name='json_data',
            field=models.JSONField(blank=True, default='', editable=False, verbose_name='Raw JSON converted data'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='parser',
            field=models.CharField(blank=True, choices=[('sensornode', 'sensornode'), ('dlmbx', 'dlmbx')], max_length=100, verbose_name='Parser'),
        ),
    ]
