# Generated by Django 3.1.3 on 2021-02-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0009_auto_20210216_1327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmessage",
            name="json_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Raw text converted data"
            ),
        ),
    ]
